In [1]:
pip install ase

Note: you may need to restart the kernel to use updated packages.


In [3]:
from ase.io import read, write
from ase.visualize import view
import numpy as np

atoms = read("geometry_estradiol.in", format="aims")

In [5]:
#setting the COM

atoms.set_center_of_mass([0.0, 0.0, 0.0], scaled=False)

In [23]:
import numpy as np

methyl = np.array([0.49803739, 2.62507462, 1.73111839])   # atom 17
carbon = np.array([0.83718779, 2.51748744, 0.23261283])   # atom 12

# Step 1: define the bond vector
vec = methyl - carbon  # vector from carbon to methyl

# Step 2: define target direction (z-axis)
target = np.array([0, 0, 1])

# Step 3: calculate angle using arccos (in radians)
def angle_between_vectors(v1, v2):
    v1_u = v1 / np.linalg.norm(v1)
    v2_u = v2 / np.linalg.norm(v2)
    dot = np.clip(np.dot(v1_u, v2_u), -1.0, 1.0)
    return np.arccos(dot)

angle_rad = angle_between_vectors(vec, target)
angle_deg = np.degrees(angle_rad)

print("Angle between methyl bond and z-axis:", angle_deg, "degrees")


Angle between methyl bond and z-axis: 13.356998956280627 degrees


In [9]:
rot_axis = np.cross(vec, [0,0,1])

atoms.rotate(13.356998956280627, rot_axis, center='COM')
view(atoms)
print(atoms[17].position)
print(atoms[12].position)

[0.88746186 2.50153922 1.7579937 ]
[0.88746186 2.50153922 0.21782588]


In [11]:
print(atoms[18].position)
print(atoms[5].position)

[-3.31110805 -4.94715423  0.2972817 ]
[-2.60756362 -3.77895374  0.10934315]


In [13]:
# Positions of OH atoms
oxygen = np.array(atoms[18].position)   # atom 18
carbon = np.array(atoms[5].position)   # atom 5

# Bond vector from carbon to oxygen
vec2 = oxygen - carbon

# Project onto XY plane
vec_xy = np.array([vec2[0], vec2[1]])

# Calculate angle (in radians)
angle_rad = np.arctan2(vec_xy[1], vec_xy[0])
angle_deg = np.degrees(angle_rad)

print("Angle between OH vector and x-axis (XY-plane):", angle_deg, "degrees")


Angle between OH vector and x-axis (XY-plane): -121.05829793786842 degrees


In [15]:
atoms.rotate(121.05829793786836, 'z', center='COM')
view(atoms)
print(atoms[18].position)
print(atoms[5].position)

[ 5.94617775 -0.28415073  0.2972817 ]
[ 4.58248162 -0.28415073  0.10934315]


In [17]:
print(atoms[17].position)
print(atoms[12].position)

[-2.60077601 -0.5303312   1.7579937 ]
[-2.60077601 -0.5303312   0.21782588]


In [19]:
atoms.rotate('x', 'z')
atoms.rotate(-90, 'z', center='COM')
view(atoms)

<Popen: returncode: None args: ['C:\\Users\\maklal.UTU\\AppData\\Local\\anac...>

In [21]:
print(atoms[18].position)
print(atoms[5].position)
print(atoms[17].position)
print(atoms[12].position)

[-0.28415073  0.2972817   5.94617775]
[-0.28415073  0.10934315  4.58248162]
[-0.5303312   1.7579937  -2.60077601]
[-0.5303312   0.21782588 -2.60077601]


In [133]:
write("estradioli_com_3D.xyz", atoms)